server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ms-auth-route
              uri: http://ms-auth-service:8082
              predicates:
                - Path=/api/ms-auth/**
            - id: ms-cms-route
              uri: http://ms-cms-service:8086
              predicates:
                - Path=/api/ms-cms/**
            - id: ms-jobs-route
              uri: http://ms-jobs-service:8087
              predicates:
                - Path=/api/ms-jobs/**
            - id: ms-products-route
              uri: http://ms-products-service:8080
              predicates:
                - Path=/api/ms-products/**

      # (Optionnel mais recommandé) Pour voir les logs de routage si ça bug
      httpclient:
        wiretap: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "product-app.local" # À restreindre en prod !
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

jwt:
  secret: ${JWT_SECRET:8w9eK7sVh3FQ2mJ6lP0rXyZtN1bQ4uDkFvHsT2cW+Eo=}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    # Pour voir les décisions de routage (quelle route est choisie)
    org.springframework.cloud.gateway: TRACE
    # Pour voir les headers et l'URI exacte envoyée vers le microservice
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    # Active le wiretap pour voir le contenu brut des échanges
    reactor.netty.http.client: DEBUG